services:
  # Spring Boot Application
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 768m
    networks:
      - spring-network
    restart: unless-stopped

networks:
  spring-network:
    driver: bridge
