services:
  # Spring Boot Native Application (GraalVM)
  spring-app-native:
    build:
      context: .
      dockerfile: Dockerfile-native
    container_name: spring-boot-app-native
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q UP || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    restart: unless-stopped
