services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
